
= Red Hat OpenShift AI: Taste of Training


== Cats and Dogs Scenario

1. In RHOAI, create a data science project.

2. Setup S3 storage in your project.
For instructions, refer to https://ai-on-openshift.io/tools-and-applications/minio/minio/#deploy-minio-in-your-project.

3. Navigate to the `minio-ui` route, log in into Minio, and create two S3 buckets:

* `cats-dogs-data`: to store the data set and the train models.
* `cats-dogs-pipelines`: to store pipeline artifacts.

4. Download the Kaggle Cats and Dogs Dataset to your computer.
You can download it from many sources:
+
--
* https://www.microsoft.com/en-us/download/details.aspx?id=54765
* `!curl -O https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip`
* https://www.kaggle.com/datasets/shaunthesheep/microsoft-catsvsdogs-dataset/data
--

5. Upload the data set zip file to your `cats-dogs-data` bucket.
This is to simulate an scenario where your data is stored in an S3 bucket.


6. Create three data connections.
Use the `minio-api` URL as the `Endpoint`.
Use the credentials that you defined in the Minio YAML (by default `minio` / `minio123`) as the access key and secret key, respectively.
Use `any` as the region.

a. `data`: this data connection connects you to the `cats-dogs-data` bucket.
b. `pipelines`: this data connection connects you to the `cats-dogs-pipelines` bucket.


7. Create a pipeline server by using the `pipelines` data connection.


8. Create a PyTorch workbench.

a. The container size must be medium and you must select one NVIDIA GPU as the accelerator.

b. Assign the `data` data connection to the workbench.


9. Open the workbench.
In the JupyterLab UI, clone the https://github.com/jramcast/rhoai-tot repository.
Navigate to `rhoai-tot/cats_dogs`.

10. Run the notebooks.

a. Run `train.ipynb` to train the model.

b. Run `evaluate.ipynb` to evaluate the training model on the test set.

c. Run `model_upload.ipynb` to upload the trained model to the `data` S3 bucket.

11. Serve the model.

a. Use the Minio UI to verify that the `model.onnx` file has been uploaded to the `models` directory of the `data` bucket.

b. On the Models tab of RHOAI, add a model server in the _Multi-model serving platform_ option.

c. Select OpenVINO Model Server as the runtime.
Select the checkbox to create an external route.
To simplify the demo, do not select the token authorization checkbox.

d. Deploy a model with the `onnx - 1` framework.
For the model location, use the `data` data connection and the path to the model in the S3 bucket, which should be similar to `models/v2024_07_03_11_07_17/model.onnx`.

e. Wait for the status of the model to be `Loaded`.

f. Copy the inference endpoint.

12. Test the deployed model.

a. Open `test.ipynb`.
Modify the `INFERENCE_ENDPOINT` variable with the endpoint that you just copied.

b. Run the notebook.

13. Use a pipeline to automate the training, evaluation, and model upload.

a. In the workbench, open the `cats-vs-dogs-pipeline` file.

b. Click the `Run Pipeline` button.

c. Wait until the pipeline finishes.

d. You can now deploy another model with the results of the pipeline.


== InstructLab Scenario


=== Setup Demo cluster

1. Add the notebook image: quay.io/jramcast/pytorch-instructlab-wb:0.17.1-python-3.9

1. Create an Instruct Large workbench with GPU.
You should add 100GB of storage.

Modify `bootstrap` ApplicationSet in `openshift-gitops` project.
Point `ic-rhoai-configuration` to https://github.com/jramcast/insurance-claim-processing



=== Instructions

1. Create a CUDA Large workbench with GPU.
You should add 100GB of storage.

1. Install with `instructlab/install.sh`

2. Clone repositories:
* https://github.com/jramcast/rhoai-tot
* https://github.com/instructlab/taxonomy

3. Generate ilab config:

----
ilab config init
----

4. Download model:

----
ilab model download
----


----
ilab sysinfo
----

----
ilab modoel train --device=cuda
----


=== Serving


SWAGGER: https://my-llm-predictor-instructlab.apps.cluster-pdskm.sandbox134.opentlc.com/docs


Consume model after serving:
----
curl -k -X 'POST' \
  'https://my-llm-predictor-instructlab.apps.cluster-pdskm.sandbox134.opentlc.com/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model": "/mnt/models/ggml-model-f16.gguf",
  "messages": [
    {
      "role": "user",
      "content": "What is the capital of France?"
    }
  ]
}'
----


== Notes

Datasets for predictive AI example:

- https://www.kaggle.com/datasets/rabieelkharoua/students-performance-dataset/code
- https://www.kaggle.com/datasets/rabieelkharoua/predict-pet-adoption-status-dataset/code
- https://www.kaggle.com/datasets/arashnic/book-recommendation-dataset
- https://www.kaggle.com/competitions/playground-series-s4e6/data
- https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success

== Notebooks

- https://www.kaggle.com/code/juwonoindo/book-recommendation-system-cbf-and-cf#==%3E-Model-Evaluation-with-Content-Based-Filtering
